version: "3.5"
services:
    zookeeper:
        container_name: zookeeper
        image: zookeeper
        ports:
            - "2181:2181"
    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "pmventura:2181"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://pmventura:9092"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        
